// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: paxoskv.proto

package src

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BallotNum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int64                  `protobuf:"varint,1,opt,name=N,proto3" json:"N,omitempty"`
	ProposerId    int64                  `protobuf:"varint,2,opt,name=ProposerId,proto3" json:"ProposerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallotNum) Reset() {
	*x = BallotNum{}
	mi := &file_paxoskv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallotNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallotNum) ProtoMessage() {}

func (x *BallotNum) ProtoReflect() protoreflect.Message {
	mi := &file_paxoskv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallotNum.ProtoReflect.Descriptor instead.
func (*BallotNum) Descriptor() ([]byte, []int) {
	return file_paxoskv_proto_rawDescGZIP(), []int{0}
}

func (x *BallotNum) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *BallotNum) GetProposerId() int64 {
	if x != nil {
		return x.ProposerId
	}
	return 0
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_paxoskv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_paxoskv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_paxoskv_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PaxosInstanceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaxosInstanceId) Reset() {
	*x = PaxosInstanceId{}
	mi := &file_paxoskv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaxosInstanceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaxosInstanceId) ProtoMessage() {}

func (x *PaxosInstanceId) ProtoReflect() protoreflect.Message {
	mi := &file_paxoskv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaxosInstanceId.ProtoReflect.Descriptor instead.
func (*PaxosInstanceId) Descriptor() ([]byte, []int) {
	return file_paxoskv_proto_rawDescGZIP(), []int{2}
}

func (x *PaxosInstanceId) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PaxosInstanceId) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Acceptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastBallot    *BallotNum             `protobuf:"bytes,1,opt,name=LastBallot,proto3" json:"LastBallot,omitempty"`
	Val           *Value                 `protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
	VBallot       *BallotNum             `protobuf:"bytes,3,opt,name=VBallot,proto3" json:"VBallot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acceptor) Reset() {
	*x = Acceptor{}
	mi := &file_paxoskv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acceptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acceptor) ProtoMessage() {}

func (x *Acceptor) ProtoReflect() protoreflect.Message {
	mi := &file_paxoskv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acceptor.ProtoReflect.Descriptor instead.
func (*Acceptor) Descriptor() ([]byte, []int) {
	return file_paxoskv_proto_rawDescGZIP(), []int{3}
}

func (x *Acceptor) GetLastBallot() *BallotNum {
	if x != nil {
		return x.LastBallot
	}
	return nil
}

func (x *Acceptor) GetVal() *Value {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *Acceptor) GetVBallot() *BallotNum {
	if x != nil {
		return x.VBallot
	}
	return nil
}

type Proposer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    *PaxosInstanceId       `protobuf:"bytes,1,opt,name=InstanceId,proto3" json:"InstanceId,omitempty"`
	Ballot        *BallotNum             `protobuf:"bytes,2,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	Val           *Value                 `protobuf:"bytes,3,opt,name=Val,proto3" json:"Val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposer) Reset() {
	*x = Proposer{}
	mi := &file_paxoskv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposer) ProtoMessage() {}

func (x *Proposer) ProtoReflect() protoreflect.Message {
	mi := &file_paxoskv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposer.ProtoReflect.Descriptor instead.
func (*Proposer) Descriptor() ([]byte, []int) {
	return file_paxoskv_proto_rawDescGZIP(), []int{4}
}

func (x *Proposer) GetInstanceId() *PaxosInstanceId {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *Proposer) GetBallot() *BallotNum {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *Proposer) GetVal() *Value {
	if x != nil {
		return x.Val
	}
	return nil
}

var File_paxoskv_proto protoreflect.FileDescriptor

const file_paxoskv_proto_rawDesc = "" +
	"\n" +
	"\rpaxoskv.proto\x12\apaxoskv\"9\n" +
	"\tBallotNum\x12\f\n" +
	"\x01N\x18\x01 \x01(\x03R\x01N\x12\x1e\n" +
	"\n" +
	"ProposerId\x18\x02 \x01(\x03R\n" +
	"ProposerId\"\x1b\n" +
	"\x05Value\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\"=\n" +
	"\x0fPaxosInstanceId\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x18\n" +
	"\aVersion\x18\x02 \x01(\x03R\aVersion\"\x8e\x01\n" +
	"\bAcceptor\x122\n" +
	"\n" +
	"LastBallot\x18\x01 \x01(\v2\x12.paxoskv.BallotNumR\n" +
	"LastBallot\x12 \n" +
	"\x03Val\x18\x02 \x01(\v2\x0e.paxoskv.ValueR\x03Val\x12,\n" +
	"\aVBallot\x18\x03 \x01(\v2\x12.paxoskv.BallotNumR\aVBallot\"\x92\x01\n" +
	"\bProposer\x128\n" +
	"\n" +
	"InstanceId\x18\x01 \x01(\v2\x18.paxoskv.PaxosInstanceIdR\n" +
	"InstanceId\x12*\n" +
	"\x06Ballot\x18\x02 \x01(\v2\x12.paxoskv.BallotNumR\x06Ballot\x12 \n" +
	"\x03Val\x18\x03 \x01(\v2\x0e.paxoskv.ValueR\x03Val2n\n" +
	"\aPaxosKV\x121\n" +
	"\aPrepare\x12\x11.paxoskv.Proposer\x1a\x11.paxoskv.Acceptor\"\x00\x120\n" +
	"\x06Accept\x12\x11.paxoskv.Proposer\x1a\x11.paxoskv.Acceptor\"\x00B\x1fZ\x1dgithub.com/ludics/paxoskv/srcb\x06proto3"

var (
	file_paxoskv_proto_rawDescOnce sync.Once
	file_paxoskv_proto_rawDescData []byte
)

func file_paxoskv_proto_rawDescGZIP() []byte {
	file_paxoskv_proto_rawDescOnce.Do(func() {
		file_paxoskv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paxoskv_proto_rawDesc), len(file_paxoskv_proto_rawDesc)))
	})
	return file_paxoskv_proto_rawDescData
}

var file_paxoskv_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_paxoskv_proto_goTypes = []any{
	(*BallotNum)(nil),       // 0: paxoskv.BallotNum
	(*Value)(nil),           // 1: paxoskv.Value
	(*PaxosInstanceId)(nil), // 2: paxoskv.PaxosInstanceId
	(*Acceptor)(nil),        // 3: paxoskv.Acceptor
	(*Proposer)(nil),        // 4: paxoskv.Proposer
}
var file_paxoskv_proto_depIdxs = []int32{
	0, // 0: paxoskv.Acceptor.LastBallot:type_name -> paxoskv.BallotNum
	1, // 1: paxoskv.Acceptor.Val:type_name -> paxoskv.Value
	0, // 2: paxoskv.Acceptor.VBallot:type_name -> paxoskv.BallotNum
	2, // 3: paxoskv.Proposer.InstanceId:type_name -> paxoskv.PaxosInstanceId
	0, // 4: paxoskv.Proposer.Ballot:type_name -> paxoskv.BallotNum
	1, // 5: paxoskv.Proposer.Val:type_name -> paxoskv.Value
	4, // 6: paxoskv.PaxosKV.Prepare:input_type -> paxoskv.Proposer
	4, // 7: paxoskv.PaxosKV.Accept:input_type -> paxoskv.Proposer
	3, // 8: paxoskv.PaxosKV.Prepare:output_type -> paxoskv.Acceptor
	3, // 9: paxoskv.PaxosKV.Accept:output_type -> paxoskv.Acceptor
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_paxoskv_proto_init() }
func file_paxoskv_proto_init() {
	if File_paxoskv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paxoskv_proto_rawDesc), len(file_paxoskv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paxoskv_proto_goTypes,
		DependencyIndexes: file_paxoskv_proto_depIdxs,
		MessageInfos:      file_paxoskv_proto_msgTypes,
	}.Build()
	File_paxoskv_proto = out.File
	file_paxoskv_proto_goTypes = nil
	file_paxoskv_proto_depIdxs = nil
}
